apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-srv
  # the entire annotation sections is helping ingress to understand that
  # we are feeding it some routing rules
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  # rules are the actual routing rules
  ingressClassName: nginx
  rules:
  # In kubernetes, you can host multiple domains
  # myposts.com below will route request to the clusterIP service for posts microservice
  # Bad news: ingress controller cannot route request based on method like GET POST, it only matches the route, 
  # so you cannot have POST /posts and GET /posts the same time
    - host: myposts.com
      http:
        paths:
          - path: /posts/create
            pathType: Prefix
            backend:
              service:
                name: posts-clusterip-srv
                port:
                  number: 4000